[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "planning-application-specification-viewer"
version = "0.0.0.dev0"
description = "Static viewer for the planning application data specification"
requires-python = ">=3.10"
dependencies = [
    "planning-application-specification",
    "jinja2",
    "markupsafe",
    "digital-land-frontend @ git+https://github.com/digital-land/digital-land-frontend.git@2e85e26209cb0380e4aa9e53a8170f5486d31d55",
    "govuk-frontend-jinja==4.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.spec-viewer]
output-directory = "docs"
